---
- debug:
    msg: "oah-install of oah.jupyer"

- name: Installing pip
  apt:
    name: python-pip
    update_cache: yes
    state: present
    
- name: Installing python-setuptools
  apt:
    name: python-setuptools
    state: present

- name: Installing jupyter lab
  pip:
    name: jupyterlab
    state: present



